### ISSUE TITLE
OMG First_part.html is BROKEN!!!!!1!

### ISSUE THREAD

**Issue by nusco** [Victor-Leroy/CYOA#1]
I want my money back! Here is what I see:

<img width="1016" alt="Screenshot 2024-02-08 at 10 32 22" src="https://github.com/Victor-Leroy/CYOA/assets/17791/1c2a3943-bd8f-46fb-b0da-960de1df416f">

**Comment by Victor-Leroy** [comment]
Thanks for pinning this issue down, could we have more details on your process of running the game?

**Comment by nusco** [comment]
Sure! I just open `index.html` in my browser. I also tried `open src/index.html` in the command line from the project root. In both cases I see broken image links after I wake up and enter the jungle.

I also tried running a server:
    
```
    npm install
    node server.js
```

The server starts, but accessing `http://localhost:3000/` takes me to an empty page and the message "Error loading the file".

**Comment by Victor-Leroy** [comment]
Alright we are sending our best investigator in order to fix this 🫡

**Comment by Victor-Leroy** [comment]
Have you tried launching the website using live server in vs code? 

If you haven't tried yet:

1. Go to VSCode extensions -> Search for [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) ID: ritwickdey.LiveServer

2. Install it and go to index.html

3. Then all you have to do is to click on that magic button on the bottom right of your screen and enjoy!

<img width="71" alt="Screenshot 2024-02-09 at 09 18 59" src="https://github.com/Victor-Leroy/CYOA/assets/97166029/010c8013-8e62-4bba-80a0-63d89d251b03">

**Comment by nusco** [comment]
Holy Cow, IT WORKS!
Also, the problem seems to have gone away. Now I can just open `index.html`, even if I explicitly turn off the server. `¯\_(ツ)_/¯`
